version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      gradle-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "com.android.application"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.android.tools.build:gradle"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.jetbrains.kotlin.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.google.devtools.ksp"
        update-types: ["version-update:semver-major"]
      - dependency-name: "androidx.compose:compose-bom"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
